### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by derhasi** [RobLoach/bowersatis#1]
Hi Rob, I just stumbled upon this project, as I'm looking for a way to integrate bower packages in our Drupal Composer workflow.

Currently we are working with https://github.com/francoispluchino/composer-asset-plugin, but this quite a slow approach and does not work from a clean installation when the plugin is not globally installed.

So I was wondering if there is a bower packagist or bower satis that mirrors the available bower package information.

Are you still using this bowersatis or do you have another approach for assets?

**Comment by RobLoach** [comment]
It's an interesting project, for sure. I believe we ended up pushing Composer support directly into some of Bower's components via http://github.com/components . Look around there, and if you don't see the component you need, feel free to:
1. Create an issue in the project itself about adding Composer support
2. Add an issue in https://github.com/components/components about creating a shim  repository

Are you looking to just download assets? How are you looking to use them?

**Comment by RobLoach** [comment]
There's also https://github.com/RobLoach/component-installer , which you can use with those components.

**Comment by derhasi** [comment]
Thanks for the help on IRC.

For summary: a lot of components from bower already are on packagist. It seems to be better to add composer support to the existing ones or create a shim repo at http://github.com/components

So, a separate bower packagist would be too much of a work, instead we simply should encourage maintainers to insert a composer.json.
